
//write code to display given string or inputed string by using left shift right dhift operator and at the last of every string must put good bye messag demostraight constuctor........
#include<iostream.h>
#include<conio.h>
#include<stdlib.h>
class demo
{
	public:
	int string,input;
	void demo(string & input)
	{
		cout<<input<<"goodbye"<<endl;
	}

};
void main()
{
	clrscr();
	demo string;
	cout<<"enter a string:";
	cin>>input;
	demo(stringdemo(input));
	getch();
}